[account]
#Total Available balance (Add a bit more for trade fees)
balance=150
#USDT to use to buy per selected token (can this be tied to current volume to avoid moving the candle too much?
spendable=20

[exchange]
name="okx"
## Enable/disable trading on exchange
enable_trading=false
#From okx fees: https://www.okx.com/fees
taker_fee=0.10
maker_fee=0.08
#Cancel open orders after (x) seconds
order_ttl=30

[exchange.authentication]
access_key=""
secret_key=""
passphrase=""

[strategy]
#Scan for the top (x) tokens
top=8
#Work with (x) amount of tokens at the same time
portfolio_size=6
#Block following tokens
#deny_list=["LUNC", "UST", "BTC", "ETH", "MAGIC", "TAI", "VALUE", "AIDOGE", "APIX", "SWRV", "MDA", "BORING", "TRUE", "XPR", "TOWN", "FODL", "WSB", "TAMA", "SKEB", "CTC", "DEVT","BNT"]

#Order Type: market or "Immediate or cancel (ioc)"
order_type="ioc"
#retrieve last(x) minutes of candlesticks to analyze the performance of tokens
timeframe=10
#time to wait before adding tokens to portfolio
cooldown=10
#Dont wait for cooldown on first round (set to false when using blank database)
quickstart=true
#Min vol to be elegible (a sane default is: timeframe * 1600 to avoid tokens with high volatility in short periods of time)
min_vol=20000
#Min change to be elegible
min_change=0.1
#Last candle should be at least this much to be eligible
min_change_last_candle=0.05
#Min/max standard deviation on selected timeframe. (std deviation coming from sum of all candles)
#Min standard deviation on selected timeframe. (std deviation coming from sum of all candles)
min_deviation=0.05
max_deviation=0.1
#sell if losing more than (x) % (optional. Will sell if token is not in top tokens when cooldown finishes)
stoploss=2.0
#Sell if earnings on selected token are above (x)%.
cashout=4.0 #token will be bought back with spendable balance if is still selected
#Only sell tokens from portfolio if earnings are above (x)% -- set to 0.3 to at least break even
sell_floor=0.45
#sell if timeout is reached, even if 'sell_above' was not met. Min timeout is 10 seconds
timeout=180
#Avoid trading a token if stoploss was triggered
avoid_after_stoploss=true

[ui]
enable=false
dashboard=true
portfolio=true
deny_list=false
balance=true
strategy=true
system=true
logs=true

[pushover]
enable=false
token=""
key=""

[server]
enable=true
listen_address="0.0.0.0"
port = 9002

[database]
ip="127.0.0.1"
port=9042
workers=8
keyspace="okx"
#Retention policy, in seconds
data_ttl=7200 # 2 hours

[mq]
ip="127.0.0.1"
port=9092

[[mq.topics]]
name = "candle1m"
partitions = 5
#Offset per topic to start retrieving messages
offset = 0
replication_factor=1
min_batch_size=1
max_batch_size=100000
max_wait_ms=500

[[mq.topics]]
name = "tickers"
partitions = 20
#Offset per topic to start retrieving messages
offset = 0
replication_factor=1
min_batch_size=1
max_batch_size=100000
max_wait_ms=500

[[mq.topics]]
name = "trades"
partitions = 10
#Offset per topic to start retrieving messages
offset = 0
replication_factor=1
min_batch_size=1
max_batch_size=100000
max_wait_ms=500
